apiVersion: v1
kind: Pod
metadata:
  name: migrator-sample-pod-1
  labels:
    name: pod-yace
spec:
  restartPolicy: Never
  nodeName: node2
  containers:
    - name: pod-yace
      command:
        - sh
        - -c
        - 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
      image: busybox
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "1"

#    containers:
#      - name: nginx
#        image: nginx:alpine
#        ports:
#          - containerPort: 80