apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespaces: default
  labels:
    app: test
spec:
  containers:
    - name: test
      image: nginx
      args:
        - ["HOSTNAME", "KUBERNETES_PORT"]
      workingdir: /
      volumeMounts:
        - name: disk1
          mountPath:
          readonly: {true|false}
      ports:
        - name: http
          containerPort: 80
          hostPort: 80
          protocol: {tcp|udp}