# permissions for end users to edit migrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: migrator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: migratorcontroller
    app.kubernetes.io/part-of: migratorcontroller
    app.kubernetes.io/managed-by: kustomize
  name: migrator-editor-role
rules:
- apiGroups:
  - migration.bupt.cjx
  resources:
  - migrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.bupt.cjx
  resources:
  - migrators/status
  verbs:
  - get
